/* eslint-disable */
// Generated by `wrangler types`. Re-run after changing wrangler.jsonc bindings.
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/worker");
    durableNamespaces: "DeviceAgent";
  }
  interface Env {
    DeviceAgent: DurableObjectNamespace<import("./src/worker").DeviceAgent>;
  }
}
interface Env extends Cloudflare.Env {}
