/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: d40fe5759cd9385a01332374b9a18f1e)
interface __BaseEnv_Env {
	HUB_PRIVATE_JWK: string;
	DeviceAgent: DurableObjectNamespace<import("./src/worker").DeviceAgent>;
	HubStore: DurableObjectNamespace<import("./src/worker").HubStore>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "DeviceAgent" | "HubStore";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "HUB_PRIVATE_JWK">> {}
}
